import { 
  MessageCircle, Send, Instagram, Facebook, Wallet, Car, 
  Twitter, Youtube, Twitch, Linkedin, Github, Mail, 
  ShoppingCart, Music, Play, Video, MapPin, 
  Globe, Gamepad2, Ghost, Lock
} from "lucide-react";

export const ALL_COUNTRIES = [
  { id: "af", name: "Afghanistan", code: "+93", flag: "🇦🇫" },
  { id: "al", name: "Albania", code: "+355", flag: "🇦🇱" },
  { id: "dz", name: "Algeria", code: "+213", flag: "🇩🇿" },
  { id: "ao", name: "Angola", code: "+244", flag: "🇦🇴" },
  { id: "ar", name: "Argentina", code: "+54", flag: "🇦🇷" },
  { id: "au", name: "Australia", code: "+61", flag: "🇦🇺" },
  { id: "at", name: "Austria", code: "+43", flag: "🇦🇹" },
  { id: "bd", name: "Bangladesh", code: "+880", flag: "🇧🇩" },
  { id: "be", name: "Belgium", code: "+32", flag: "🇧🇪" },
  { id: "br", name: "Brazil", code: "+55", flag: "🇧🇷" },
  { id: "bg", name: "Bulgaria", code: "+359", flag: "🇧🇬" },
  { id: "kh", name: "Cambodia", code: "+855", flag: "🇰🇭" },
  { id: "cm", name: "Cameroon", code: "+237", flag: "🇨🇲" },
  { id: "ca", name: "Canada", code: "+1", flag: "🇨1" },
  { id: "cn", name: "China", code: "+86", flag: "🇨🇳" },
  { id: "co", name: "Colombia", code: "+57", flag: "🇨🇴" },
  { id: "hr", name: "Croatia", code: "+385", flag: "🇭🇷" },
  { id: "cy", name: "Cyprus", code: "+357", flag: "🇨🇾" },
  { id: "cz", name: "Czech Republic", code: "+420", flag: "🇨🇿" },
  { id: "dk", name: "Denmark", code: "+45", flag: "🇩🇰" },
  { id: "eg", name: "Egypt", code: "+20", flag: "🇪🇬" },
  { id: "ee", name: "Estonia", code: "+372", flag: "🇪🇪" },
  { id: "et", name: "Ethiopia", code: "+251", flag: "🇪🇹" },
  { id: "fi", name: "Finland", code: "+358", flag: "🇫🇮" },
  { id: "fr", name: "France", code: "+33", flag: "🇫🇷" },
  { id: "ge", name: "Georgia", code: "+995", flag: "🇬🇪" },
  { id: "de", name: "Germany", code: "+49", flag: "🇩🇪" },
  { id: "gh", name: "Ghana", code: "+233", flag: "🇬🇭" },
  { id: "gr", name: "Greece", code: "+30", flag: "🇬🇷" },
  { id: "hk", name: "Hong Kong", code: "+852", flag: "🇭🇰" },
  { id: "hu", name: "Hungary", code: "+36", flag: "🇭🇺" },
  { id: "in", name: "India", code: "+91", flag: "🇮🇳" },
  { id: "id", name: "Indonesia", code: "+62", flag: "🇮🇩" },
  { id: "ir", name: "Iran", code: "+98", flag: "🇮🇷" },
  { id: "iq", name: "Iraq", code: "+964", flag: "🇮🇶" },
  { id: "ie", name: "Ireland", code: "+353", flag: "🇮🇪" },
  { id: "il", name: "Israel", code: "+972", flag: "🇮🇱" },
  { id: "it", name: "Italy", code: "+39", flag: "🇮🇹" },
  { id: "jp", name: "Japan", code: "+81", flag: "🇯🇵" },
  { id: "ke", name: "Kenya", code: "+254", flag: "🇰🇪" },
  { id: "lv", name: "Latvia", code: "+371", flag: "🇱🇻" },
  { id: "my", name: "Malaysia", code: "+60", flag: "🇲🇾" },
  { id: "mx", name: "Mexico", code: "+52", flag: "🇲🇽" },
  { id: "ma", name: "Morocco", code: "+212", flag: "🇲🇦" },
  { id: "nl", name: "Netherlands", code: "+31", flag: "🇳🇱" },
  { id: "nz", name: "New Zealand", code: "+64", flag: "🇳🇿" },
  { id: "ng", name: "Nigeria", code: "+234", flag: "🇳🇬" },
  { id: "no", name: "Norway", code: "+47", flag: "🇳🇴" },
  { id: "pk", name: "Pakistan", code: "+92", flag: "🇵🇰" },
  { id: "ph", name: "Philippines", code: "+63", flag: "🇵🇭" },
  { id: "pl", name: "Poland", code: "+48", flag: "🇵🇱" },
  { id: "pt", name: "Portugal", code: "+351", flag: "🇵🇹" },
  { id: "ro", name: "Romania", code: "+40", flag: "🇷🇴" },
  { id: "ru", name: "Russia", code: "+7", flag: "🇷🇺" },
  { id: "sa", name: "Saudi Arabia", code: "+966", flag: "🇸🇦" },
  { id: "sg", name: "Singapore", code: "+65", flag: "🇸🇬" },
  { id: "za", name: "South Africa", code: "+27", flag: "🇿🇦" },
  { id: "kr", name: "South Korea", code: "+82", flag: "🇰🇷" },
  { id: "es", name: "Spain", code: "+34", flag: "🇪🇸" },
  { id: "se", name: "Sweden", code: "+46", flag: "🇸🇪" },
  { id: "ch", name: "Switzerland", code: "+41", flag: "🇨🇭" },
  { id: "tw", name: "Taiwan", code: "+886", flag: "🇹🇼" },
  { id: "th", name: "Thailand", code: "+66", flag: "🇹🇭" },
  { id: "tr", name: "Turkey", code: "+90", flag: "🇹🇷" },
  { id: "ua", name: "Ukraine", code: "+380", flag: "🇺🇦" },
  { id: "ae", name: "United Arab Emirates", code: "+971", flag: "🇦🇪" },
  { id: "uk", name: "United Kingdom", code: "+44", flag: "🇬🇧" },
  { id: "us", name: "United States", code: "+1", flag: "🇺🇸" },
  { id: "vn", name: "Vietnam", code: "+84", flag: "🇻🇳" },
  { id: "zm", name: "Zimbabwe", code: "+263", flag: "🇿🇼" }
];

export const ALL_SERVICES = [
  { id: "wa", name: "WhatsApp", price: 450, icon: MessageCircle, color: "text-green-500" },
  { id: "tg", name: "Telegram", price: 350, icon: Send, color: "text-blue-500" },
  { id: "ig", name: "Instagram", price: 150, icon: Instagram, color: "text-pink-500" },
  { id: "fb", name: "Facebook", price: 200, icon: Facebook, color: "text-blue-600" },
  { id: "tw", name: "Twitter / X", price: 250, icon: Twitter, color: "text-black dark:text-white" },
  { id: "tt", name: "TikTok", price: 180, icon: Video, color: "text-pink-600" },
  { id: "go", name: "Google / Gmail", price: 300, icon: Mail, color: "text-red-500" },
  { id: "yt", name: "YouTube", price: 220, icon: Youtube, color: "text-red-600" },
  { id: "nf", name: "Netflix", price: 120, icon: Play, color: "text-red-700" },
  { id: "am", name: "Amazon", price: 200, icon: ShoppingCart, color: "text-orange-500" },
  { id: "pp", name: "PayPal", price: 600, icon: Wallet, color: "text-blue-800" },
  { id: "ub", name: "Uber", price: 250, icon: Car, color: "text-main" },
  { id: "li", name: "LinkedIn", price: 400, icon: Linkedin, color: "text-blue-700" },
  { id: "sc", name: "Snapchat", price: 180, icon: Ghost, color: "text-yellow-400" },
  { id: "dc", name: "Discord", price: 220, icon: Gamepad2, color: "text-indigo-500" },
  { id: "sp", name: "Spotify", price: 150, icon: Music, color: "text-green-600" },
  { id: "ai", name: "OpenAI / ChatGPT", price: 550, icon: Lock, color: "text-teal-600" },
  { id: "ab", name: "Airbnb", price: 300, icon: MapPin, color: "text-red-500" },
  { id: "gh", name: "GitHub", price: 300, icon: Github, color: "text-main" },
  { id: "tc", name: "Twitch", price: 200, icon: Twitch, color: "text-purple-500" },
  { id: "ms", name: "Microsoft", price: 280, icon: Globe, color: "text-blue-400" },
  { id: "co", name: "Coinbase", price: 500, icon: Wallet, color: "text-blue-600" },
];
